DI
hamy11/di pull request #1
Opened 2017-12-05 17:15 UTC by hamy11

2017-12-05 18:05 UTC, hamy11 commented
@Qoter

2017-12-09 22:01 UTC, qoter requested changes

2017-12-09 22:01 UTC, qoter commented on TagsCloudVisualisation/README.md
> +![TagCloud](https://i.imgur.com/hL0Mg0T.png)
Что-то картинка не отображается(
Кстати, картинки можно загрузить прямо в репозиторий

2017-12-09 22:01 UTC, qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/packages.config
>  </packages>
NUnit куда-то потерялся из пакетов. Из-за этого проект не собирается(

2017-12-09 22:01 UTC, qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/ArchimedianSpiralPlacer/ArchimedeanSpiralPlacer.cs
> +        public ArchimedeanSpiralPlacer(Point center, IArchimedeanSpiralPlacerSettings settings)
сenter лучше тоже в настройки засунуть

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/WordContainer.cs
>      public class WordContainer
Здесь тоже нужен интерфейс)

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/WordProcessors/WordLowerCaser.cs
> +    public class WordLowerCaser : IWordProcessor
Можно было выделить две разные абстракции: IWordsProcessor - обрабатывает слова, IWordsFilter - фильтрует.
Хотя, в целом, и так хорошо)

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/WordProcessors/BoringWordRemover.cs
> +            return datas.Where(x => x.WordCount > 0);
Как слово, которое встречается 0 раз, попадает сюда?

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/WordScaleInfo.cs
> +    public class WordScaleInfo
Какой-то странный класс, есть ведь уже WordPrintingInfo. Этот класс нужно убрать, либо использовать его как свойство в WordPrintingInfo

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/WordContainer.cs
> +            foreach (var processor in processors)
foreach можно заменить на LINQ Aggregate

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/CloudVisualizer.cs
> +        public WordScaleInfo GetWordScaleInfo(WordData word)
Visulizer'a не должен заниматься вычислением размера слова, нужно выделить отдельную абстракцию.

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/CloudVisualizer.cs
> +        public readonly Graphics Graphics;
Зачем public?

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/CloudVisualizer.cs
>      public class CloudVisualizer
Нужен интерфейс, не принято через DI делать resolve конкретных классов

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/CloudGenerator.cs
>      public class CloudGenerator
Тоже нужен интерфейс

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => new Point(500, 500)).AsSelf().SingleInstance();
Ох, очень странно регистрировать точку. Если, вдруг, кто примет в конструкторе точку то...

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => new FileInfo("in.txt", FileFormat.None)).As<FileInfo>().SingleInstance();
Такая же фигня, что и с точкой

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => new VisualizeSettings()).As<IVisualizeSettings>().SingleInstance();
AsImplementedInterfaces()

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => c.Resolve<CloudGenerator>().GenerateCloud())
Странный код, чтоб его понять, приходится искать где зарегистрировали CloudGenerator.
Хочется какой-то абстракции, типо ICloudProvider, но Visualizer оставить многоразовым (то есть принимающим Cloud в методе Visualize(..))
Регистрация, чего-то на конкретную реализацию, может привести к ошибкам, если, кто-то будет принимать реализацию в конструкторе (что тоже не очень хорошо)

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +                .As<Cloud>();
Есть AsSelf, но здесь он не нужен

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/ArchimedianSpiralPlacerShould.cs
> +        public void TestTearDown()
Просто TearDown()

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/ArchimedianSpiralPlacerShould.cs
> +            rnd = new Random();
Random-у лучше передать seed, иначе могут появиться мигающие тесты

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/ArchimedianSpiralPlacerShould.cs
> +        [TestCase(100, 5, 30, 5, 10, TestName = "100 ��������������� � ��������� 5<x<30 5<y<10")]
Что-то с кодировкой в этом файле

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CircularCloudLayouterShould.cs
> +            new Rectangle(p, size).ShouldBeEquivalentTo(nextRectangle);
Здесь тестируется Mock библиотека? Зачем?

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CircularCloudLayouterShould.cs
> +        }
Хорошо, можно добавить ещё поведенческих тестов (на взаимодействие классов между собой), хотяб ещё чуть чуть))

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CircularCloudLayouterShould.cs
> +        }
Нужен ещё модульный тест, проверяющий работу программы в целом

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/packages.config
>  </packages>
```
Организуй код так, чтобы было легко сделать оба вида клиентов — и клиента командной строки,
и GUI приложение с вводом параметров и интерактивным просмотром.
```
Тут подразумевается выделения какой-то абстракции

2017-12-09 22:01 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            visualizer.Visualize(cloud, "WordCloud");
В идеале делать Resolve один раз

2017-12-14 10:32 UTC, qoter approved these changes
В целом стало получше, но не идеально. Так как дедлайн уже прошёл, то принимаю задачу (чтоб не затягивать).

2017-12-14 10:32 UTC, qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
>  ﻿#region
region здесь не нужен, using'и и так можно свернуть

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.RegisterType<XmlObjectSerializer>().As<IObjectSerializer>().SingleInstance();
Можно было в json, он более читаемый, но и так круто)

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => c.Resolve<AppSettings>().VisualizeSettings).As<IVisualizeSettings>().SingleInstance();
Используй везде AsImplementedInterfaces().

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => c.Resolve<AppSettings>().VisualizeSettings).As<IVisualizeSettings>().SingleInstance();
Есть ещё, кажется, такая штука RegisterAssemblyTypes(...). Было бы круто, настраивать весь контейнер, вызвав один метод))

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/WordScaler.cs
> +            graphics = Graphics.FromImage(bitmap);
С двумя graphics, не очень. Тут подразумевается, что размер изображения всегда один.
Можно было ещё заюзать TextRenderer.MeasureText(..), но он даёт немного не точный результат

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Settings/VisualizeSettings.cs
> +        [XmlIgnore]// не умеет сериализовать цвета :/
Наверное, можно настроить, у тебя ведь есть класс, который отвечает за сериализацию

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Program.cs
> +            builder.Register(c => c.Resolve<ICloudGenerator>().GenerateCloud()).As<Cloud>();
CloudProvider мог бы и сам этот метод дёрнуть. Так получилось, что у тебя всегда одно и тоже облако.

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/ArchimedianSpiralPlacerShould.cs
> +        [TestCase(100, 5, 5, TestName = "����� 100 ��������� �� �������� 5")]
Кодировку чинить надо)))

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CloudGeneratorShould.cs
> +        public void GenerateCloud_ShouldReturnFivePrintDataObjects_WhenWordsCountIsFive()
Можно просто `ReturnFivePrintDataObjects_WhenWordsCountIsFive`

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CloudGeneratorShould.cs
> +            TestReader.WordsCount = 5;
Обычно создание моков выносят в SetUp, а в тесте уже настраивается

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CloudGeneratorShould.cs
> +        {
`CallLayouterAndScaler_ExactlyTimes`, ну или что-то типо того, а то слишком длинно

2017-12-14 10:32 UTC, Qoter commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CloudGeneratorShould.cs
> +        }
У тебя если тесты на поведение CloudGenerator, то не нужно ему реализации передавать, должны быть моки. Или нужно разделить эти тесты

2017-12-14 17:47 UTC, merged